### ISSUE TITLE
Initial suggestions for plugin release. Continue on issue #1

### ISSUE THREAD

**Issue by madhushreeray30** [ajmaradiaga/steampipe-plugin-btp#3]
Hey @ajmaradiaga Few things that we are missing out on this plugin are listed out, can you please work on them and then we can get it on the hub as soon as possible :
1. Can you remove the //Endpoints and //username comments as the variables are good enough to understand > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/btp/connection_config.go#L13
2. Why have we kept the required : false in access_token? Is it not a required parameter? >https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/btp/connection_config.go#L28
3. Does this fetch a single result ? > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/btp/table_btp_accounts_global_account.go#L42 why do we have a get call in a list config?. Since you are streamlisting I believe this gives all teh global accounts, so can you please rename it to listGlobalAccounts
4. Instead of using * can you please mention the important columns> 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_directory.md?plain=1#L11
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L11
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L20
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L31
5. I don't think we need the connection name to be mentioned here just the table name (btp_accounts_directory) would be good as the connection name may vary depending on the number of connections someone is using > 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_directory.md?plain=1#L13
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_global_account.md?plain=1#L22 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_subaccount.md?plain=1#L85
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L22
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L33C1-L33C1
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L57
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/index.md?plain=1#L28
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/README.md?plain=1#L67
6. I think we can have 1-2 more example queries for the table btp_accounts_global_account like eg : List the global accounts create din the last  7 days, List the consumption-based global accounts, List all suspended global accounts, etc.
7. What does the distinct do here is it only on the parent_guid? If so then we should put it in the second column, But why do we need it? > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_subaccount.md?plain=1#L42
8. Please remove this extra line > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_accounts_subaccount.md?plain=1#L90
9. We do not need an alias when we have only one table with no joins > 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_assignment.md?plain=1#L13 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_assignment.md?plain=1#L23
10. Why do we need the distinct here? Again can you please write it in the next line as distinct business_category ->> 'id' as bc_id if the distinct is needed. > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_assignment.md?plain=1#L10
11. Please change the WHERE to lower case > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/tables/btp_entitlements_datacenter.md?plain=1#L23
12. Is the query output correct? The created_date and modified_date is not in date format > 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/index.md?plain=1#L35
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/README.md?plain=1#L74
13. The credential section should have all 4 > Credentials, Permissions, Radius, Resolution.> https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/index.md?plain=1#L55
14. The get involved section should contain - Community: [Join #steampipe on Slack →](https://turbot.com/community/join) as well > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/index.md?plain=1#L95
15. The install command is incorrect it should be > steampipe plugin install ajmaradiaga/btp
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/docs/index.md?plain=1#L50 
- https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/README.md?plain=1#L16
16. The community link is missing after documentation - Community: [Slack Channel](https://steampipe.io/community/join)  > https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/316ef2c211838a9d58ce9fcbde038b59e2c10042/README.md?plain=1#L6C1-L6C1

Please reach out to us in case of any don't, thanks!

**Comment by ajmaradiaga** [comment]
@madhushreeray30, thanks for reviewing again the plugin.... See below a summary of the changes and explaining a couple of items.
1. ✅ Removed 
2. ✅ Removed
3. I've used get calls in other tables, e.g. subaccount(https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/9a7227e482924f71107154e5baf3ad92d2529390/btp/table_btp_accounts_subaccount.go#L94) and [directory](https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/9a7227e482924f71107154e5baf3ad92d2529390/btp/table_btp_accounts_directory.go#L46) and I'm using a list here because there is no way of getting a single global account at the moment and the plugin.GetConfig [requires setting a KeyColumn](https://github.com/turbot/steampipe-plugin-sdk/blob/ceaf92cebe80c43911ced82cd880ee9e647c7f65/plugin/get_config.go#L141C5-L141C5), which is not applicable in this case. Although the API is returning a single record... _Note: You can see this in the [API documentation](https://hub.sap.com/api/APIAccountsService/resource/Global_Account_Operations). It could be that the API in the future might be able to return multiple global accounts but at the moment it only returns a single global account._
4. ✅ Included columns.
5. ✅ Removed connection name.
6. At the moment that API will return a single record. Hence why adding additional query examples might not make much sense.
7. That query is against the subaccounts table which can return many records. There is a particular field (parent_guid) within those records that will be repeated, it identifies the directory that the subaccount is part of. If we are interested in knowing just the different directories that are part of a global account, we need to do a distinct based on this field.
8. ✅ Removed.
9. ✅ Removed.
10. The services in SAP BTP have a business category assigned to them. This query is just to see the different business categories that a service can be part of.
11. ✅ Fixed.
12. The sample value is correct, the API returns a Unix timestamp.
13. ✅ Included premissions and radius records in the table.
14. ✅ Included the community link.
15. ✅ Fixed the plugin install instruction.
16. ✅ Added the community link.

**Comment by ajmaradiaga** [comment]
✅ Added social graphic to README - https://github.com/ajmaradiaga/steampipe-plugin-btp/commit/a63f6af18f826af01ad60eb6c111eb41b7068d8f

**Comment by ajmaradiaga** [comment]
Closing this issue as all items have been addressed.
